INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_PACKETDECODERSDR PacketDeCoderSDR)

FIND_PATH(
    PACKETDECODERSDR_INCLUDE_DIRS
    NAMES PacketDeCoderSDR/api.h
    HINTS $ENV{PACKETDECODERSDR_DIR}/include
        ${PC_PACKETDECODERSDR_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    PACKETDECODERSDR_LIBRARIES
    NAMES gnuradio-PacketDeCoderSDR
    HINTS $ENV{PACKETDECODERSDR_DIR}/lib
        ${PC_PACKETDECODERSDR_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PACKETDECODERSDR DEFAULT_MSG PACKETDECODERSDR_LIBRARIES PACKETDECODERSDR_INCLUDE_DIRS)
MARK_AS_ADVANCED(PACKETDECODERSDR_LIBRARIES PACKETDECODERSDR_INCLUDE_DIRS)

